version: '3.5'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
