version: '3'
services:
  # nginx: 
  #   image: nginx:latest
  #   container_name: production_nginx
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - ./config/deploy:/etc/nginx/letsencrypt/
  #   ports:
  #     - 80:80
  #     - 443:443
  #   env_file:
  #     - ./config/common.env
  #   environment:
  #     - ENV=development
  #     - APPLICATION_URL=http://web.2

  # nginx.2:
  #   container_name: nginx.2
  #   image: webapp-nginx
  #   build:
  #     context: .
  #     dockerfile: nginx.Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web.2
  #   volumes:
  #     - "./web.2:/usr/src/app"
  #     - "./config/deploy:/etc/letsencrypt"
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf

  web.2:
    container_name: web.2
    build: ./web.2
    restart: on-failure
    volumes:
      - "./uploads:/usr/src/app/uploads"
    ports:
      - 80:5000
    depends_on:
      - db.2
    env_file:
      - ./config/flask.cfg
      
  db.2:
    container_name: db.2
    image: mongo:latest
    restart: on-failure
    # volumes:
    #   - "./db:/data/db"
 
