version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_01
    ports:
      - "8000:9000"
    volumes:
      - ./src:/code      
      - ./src/static:/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - ./db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput"
    command: sh start.sh
    volumes:
      - ./src:/code
      - ./src/media:/code/media
      - ./src/static:/code/static
    expose:
      - 8000
    environment:
      - ./config/.env.secret
    depends_on:
      - db
