version: '3'
services:
  web:
    build: ./web
    ports:
      - "6000:5000"
    links:
      - db
  db:
    image: mongo:latest
    volumes:
      - "./db:/data/db"
    ports:
      - "27017:27017"
    command: mongod
 
