version: '3'
services:
  # nginx: 
  #   image: nginx:latest
  #   container_name: production_nginx
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf
  #     - ./config/deploy:/etc/nginx/letsencrypt/
  #   ports:
  #     - 80:80
  #     - 443:443
  #   env_file:
  #     - ./config/common.env
  #   environment:
  #     - ENV=development
  #     - APPLICATION_URL=http://web.1

  web.1:
    container_name: web.1
    build: ./web.2
    restart: on-failure
    volumes:
      - "./uploads:/usr/src/app/uploads"
    ports:
      - "7000:5000"
    expose:
      - 7000
    depends_on:
      - db.1
      
  db.1:
    container_name: db.1
    image: mongo:latest
    restart: on-failure
    # volumes:
    #   - "./db:/data/db"
 
