version: '3'
services:
  web.1:
    container_name: web
    build: ./web.2
    restart: on-failure
    volumes:
      - "./uploads:/usr/src/app/uploads"
    ports:
      - "7000:5000"
    expose:
      - 7000
    depends_on:
      - db.1
  db.1:
    container_name: db.1
    image: mongo:latest
    restart: on-failure
    command: mongod --port 27017
    # volumes:
    #   - "./db:/data/db"
    expose:
      - 27017
    ports:
      - "27017:27017"
 
